# Table of Contents
 <p><div class="lev1"><a href="#Import-pandas,-numpy,-matplotlib-and-seaborn"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import pandas, numpy, matplotlib and seaborn</a></div><div class="lev1"><a href="#Create-a-Series-object,-access-it's-index-and-cells"><span class="toc-item-num">2&nbsp;&nbsp;</span>Create a Series object, access it's index and cells</a></div><div class="lev1"><a href="#Create-a-DataFrame-object,-access-its-rows,-columns,-indices,-cells"><span class="toc-item-num">3&nbsp;&nbsp;</span>Create a DataFrame object, access its rows, columns, indices, cells</a></div><div class="lev1"><a href="#Data-Import"><span class="toc-item-num">4&nbsp;&nbsp;</span>Data Import</a></div><div class="lev1"><a href="#DataFrame-filtering"><span class="toc-item-num">5&nbsp;&nbsp;</span>DataFrame filtering</a></div><div class="lev1"><a href="#Data-export"><span class="toc-item-num">6&nbsp;&nbsp;</span>Data export</a></div><div class="lev1"><a href="#DataFrame-aggregation"><span class="toc-item-num">7&nbsp;&nbsp;</span>DataFrame aggregation</a></div><div class="lev1"><a href="#Data-Merging"><span class="toc-item-num">8&nbsp;&nbsp;</span>Data Merging</a></div>

This notebook is to quickly repeat the most basic pandas operations prior to starting the practical course.
You should be able to quickly perform the following tasks before you start working on the exercises in the Day1 notebook. If you need to look up, how certain problems can be solved, have a look at the pandas [10 Minutes Introduction](http://pandas.pydata.org/pandas-docs/stable/10min.html), the [tutorials](http://pandas.pydata.org/pandas-docs/stable/tutorials.html) and the lecture slides.

# Import pandas, numpy, matplotlib and seaborn

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# Create a Series object, access it's index and cells

Create a Series object representing the following measurements

| S   |
|-----|
| 1.0 |
| 1.5 |
| 3.0 |
| 4.3 |
| 8.2 |

In [3]:
S = pd.Series([1., 1.5, 3., 4.3, 8.2])

In [10]:
S.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
S.values

array([ 1. ,  1.5,  3. ,  4.3,  8.2])

# Create a DataFrame object, access its rows, columns, indices, cells

Create a dataframe of the following table.

|index   |a |b  |c   |d          |e |
|--------|--|---|----|-----------|--|
|1       |2 |3  |5.  |horse      |13|
|2       |3 |1  |1.4 |cat        |11|
|3       |4 |9  |1.2 |dog        |  |
|4       |5 |12 |0.8 |tortoise   |  |
|5       |6 |2  |2.3 |rabbit     |9 |

Now
* access the values of each row individually
* access single cells
* print the index and column names
* access values of each column individually
* rename columns
* extract rows 2-4 as new dataframe
* obtain summary table of dataframe

Create the dataframe df.

In [102]:
df = pd.DataFrame({
        "a" : range(2,7),
        "b" : [3,1,9,12,2],
        "c" : [5., 1.4, 1.2, .8, 2.3],
        "d" : ["horse", "cat", "dog", "tortoise", "rabbit"],
        "e" : [13, 11, np.nan, np.nan, 9]
    }, index = range(1,6))

Access the values of each row individually, e.g. row number 3

In [65]:
df.values[2]

array([4, 9, 1.2, 'dog', nan], dtype=object)

access single cells, e.g. cell of column a in row 3

In [41]:
df["a"][2]

3

print the index and column names

In [45]:
df.index

Int64Index([1, 2, 3, 4, 5], dtype='int64')

In [46]:
df.columns

Index([u'a', u'b', u'c', u'd', u'e'], dtype='object')

access values of each column individually, e.g. column a

In [47]:
df["a"].values

array([2, 3, 4, 5, 6])

rename a column, e.g. column a to shift index

In [103]:
df.rename(columns={"a": "shift index"}, inplace = True)
df

shift index   b    c         d     e
1            2   3  5.0     horse  13.0
2            3   1  1.4       cat  11.0
3            4   9  1.2       dog   NaN
4            5  12  0.8  tortoise   NaN
5            6   2  2.3    rabbit   9.0

extrat rows 2-4 into another data frame, named dfExtr, just the first row remains in df

In [104]:
dfExtr = df.ix[2:,:].copy()
dfExtr

shift index   b    c         d     e
2            3   1  1.4       cat  11.0
3            4   9  1.2       dog   NaN
4            5  12  0.8  tortoise   NaN
5            6   2  2.3    rabbit   9.0

Obtain summary table of the dataframe, e.g. of dfExtr

In [101]:
dfExtr.describe()

shift index          b         c          e
count     4.000000   4.000000  4.000000   2.000000
mean      4.500000   6.000000  1.425000  10.000000
std       1.290994   5.354126  0.634429   1.414214
min       3.000000   1.000000  0.800000   9.000000
25%       3.750000   1.750000  1.100000        NaN
50%       4.500000   5.500000  1.300000        NaN
75%       5.250000   9.750000  1.625000        NaN
max       6.000000  12.000000  2.300000  11.000000

# Data Import

Import the following file into a dataframe _df2_:

https://raw.githubusercontent.com/cschaerfe/PIBI/master/example_data/example_df.csv?token=AC7j1EQvTFcnGxOxN0s7SKGaZbaw-AEhks5X4VAvwA%3D%3D

In [176]:
df2 = pd.read_csv("https://raw.githubusercontent.com/cschaerfe/PIBI/master/example_data/example_df.csv?token=AC7j1EQvTFcnGxOxN0s7SKGaZbaw-AEhks5X4VAvwA%3D%3D")
df2

a   b    c         d     e
0  2   3  5.0     horse  13.0
1  3   1  1.4       cat  11.0
2  4   9  1.2       dog   NaN
3  5  12  0.8  tortoise   NaN
4  6   2  2.3    rabbit   9.0

Now import the following file into a pandas dataframe _df3_. Do you need to change some parameters of the funtion?
Check whether import makes sense by showing the dataframe

https://raw.githubusercontent.com/cschaerfe/PIBI/master/example_data/example_df2.csv?token=AC7j1IqAY5PTE1Iadona7kkl6e6Fs4Krks5X4VOIwA%3D%3D

the dataframe in this link is separated with ";" instead of ",". Therefore the separator has manually be changed to ";".

In [110]:
df3 = pd.read_csv("https://raw.githubusercontent.com/cschaerfe/PIBI/master/example_data/example_df2.csv?token=AC7j1IqAY5PTE1Iadona7kkl6e6Fs4Krks5X4VOIwA%3D%3D", sep=';')
df3

a   b    c         d     e
0  2   3  5.0     horse  13.0
1  3   1  1.4       cat  11.0
2  4   9  1.2       dog   NaN
3  5  12  0.8  tortoise   NaN
4  6   2  2.3    rabbit   9.0

# DataFrame filtering
Using the dataframe created in section 3:

* select rows containing values greater than 2 in the 3rd column
* select rows that contain values greater than 2 in the 3rd column or 'cat' in the 4th column
* drop rows with missing data
* drop duplicate rows
* drop 1st column from dataframe
* sort rows by 2nd column
* convert Strings in 4th column to title-case

Select rows containing values greater than 2 in the 3rd column

In [124]:
df2[df2.ix[:, 2] > 2]

a  b    c       d     e
0  2  3  5.0   horse  13.0
4  6  2  2.3  rabbit   9.0

select rows that contain values greater than 2 in the 3rd column o 'cat' in the 4th column

In [139]:
df2[(df2.ix[:, 2] > 2) | (df2.ix[:, 3] == 'cat')]

a  b    c       d     e
0  2  3  5.0   horse  13.0
1  3  1  1.4     cat  11.0
4  6  2  2.3  rabbit   9.0

drop rows with missing data

In [177]:
df2.dropna(how = "any", inplace = True)
df2

a  b    c       d     e
0  2  3  5.0   horse  13.0
1  3  1  1.4     cat  11.0
4  6  2  2.3  rabbit   9.0

drop dupliacated rows

In [178]:
df2.drop_duplicates()

a  b    c       d     e
0  2  3  5.0   horse  13.0
1  3  1  1.4     cat  11.0
4  6  2  2.3  rabbit   9.0

drop first column of dataframe, by the index of the first column, not its name

In [179]:
df2.drop(df2.columns.values[0], axis=1)

b    c       d     e
0  3  5.0   horse  13.0
1  1  1.4     cat  11.0
4  2  2.3  rabbit   9.0

sort rows by second column, again by the index of the column, no its name

In [180]:
df2.sort_values(by=df2.columns.values[1])

a  b    c       d     e
1  3  1  1.4     cat  11.0
4  6  2  2.3  rabbit   9.0
0  2  3  5.0   horse  13.0

convert Strings in fourth column to title-case

In [184]:
df2[df2.columns.values[3]] = df2[df2.columns.values[3]].str.title()
df2

a  b    c       d     e
0  2  3  5.0   Horse  13.0
1  3  1  1.4     Cat  11.0
4  6  2  2.3  Rabbit   9.0

# Data export

Export your filtered dataframe as a text file separated by tabs omitting the index column.

In [188]:
df2.to_csv(r'pandas.txt', sep='\t', index = False)

# DataFrame aggregation

Using _df4_, group the data by column 'b'. Test different ways of aggregating the remaining columns as shown in the lecture.

In [211]:
df4 = pd.read_csv("https://raw.githubusercontent.com/cschaerfe/Integrated_Bioinformatics/master/example_data/df4.csv")
grouped = df4.groupby("b")

test different aggregation methods

In [213]:
grouped.agg({np.sum})

c                d     e
         sum              sum   sum
b                                  
fish     2.7  goldfishkoicarp  10.0
mammal   7.6      horsecatdog  24.0
reptile  2.3            snake   9.0

In [215]:
grouped.agg({"c" : np.mean, "e" : np.max})

c     e
b                      
fish     0.900000  10.0
mammal   2.533333  13.0
reptile  2.300000   9.0

In [221]:
grouped.agg({"c": {"mean" : np.mean, "max" : np.max},
             "e": {"mean" : np.mean, "min" : np.min},
             "d": {"sum" : np.sum, "max" : np.max}})

c               e            d                 
         max      mean   min  mean    max              sum
b                                                         
fish     1.8  0.900000  10.0  10.0    koi  goldfishkoicarp
mammal   5.0  2.533333  11.0  12.0  horse      horsecatdog
reptile  2.3  2.300000   9.0   9.0  snake            snake

# Data Merging

* Merge df3 with df4 on columns c, d and e. Change columns with same names in a meaningful way.

In [227]:
merged = pd.merge(df3, df4, on = ["c", "d", "e"], suffixes = ("_numbers", "_animals"))
merged

a  b_numbers    c      d     e b_animals
0  2          3  5.0  horse  13.0    mammal
1  3          1  1.4    cat  11.0    mammal
2  4          9  1.2    dog   NaN    mammal

* Now perform a full outer join of the data, to keep all rows contained in either of the two dataframes.

In [226]:
full_outer = pd.merge(df3, df4, how = "outer")
full_outer

a        b    c         d     e
0   2.0        3  5.0     horse  13.0
1   3.0        1  1.4       cat  11.0
2   4.0        9  1.2       dog   NaN
3   5.0       12  0.8  tortoise   NaN
4   6.0        2  2.3    rabbit   9.0
5   NaN   mammal  5.0     horse  13.0
6   NaN   mammal  1.4       cat  11.0
7   NaN   mammal  1.2       dog   NaN
8   NaN     fish  0.1  goldfish   NaN
9   NaN  reptile  2.3     snake   9.0
10  NaN     fish  1.8       koi  10.0
11  NaN     fish  0.8      carp   NaN